SIBKMNETMvc_WebApp/Models/Province.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace SIBKMNETMvc_WebApp.Models
{
    public class Province
    {
        [Key]
        public int Id { get; set; }

        public string Name { get; set; }
        
        //create instanceObject Class
        public Region Region { get; set; }
        [ForeignKey("Region")]
        public int RegionId { get; set; }
    }
}

SIBKMNETMvc_WebApp/Controllers/ProvinceController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SIBKMNETMvc_WebApp.Context;
using SIBKMNETMvc_WebApp.Models;
using SIBKMNETMvc_WebApp.Repositories.Data;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Threading.Tasks;

namespace SIBKMNETMvc_WebApp.Controllers
{
    public class ProvinceController : Controller
    {
        ProvinceRepository ProvinceRepository;

        public ProvinceController(ProvinceRepository ProvinceRepository)
        {
            this.ProvinceRepository = ProvinceRepository;
        }

        Province province = new Province();
        //GET ALL
        //GET
        public IActionResult Index()
        {
            //var data = myContext.Provinces.Include(x => x.Region).ToList(); //untuk get data dari database menggunakan entity framework core
            string role = HttpContext.Session.GetString("Role");
            if (role.Equals("Admin"))
            {
                var data = ProvinceRepository.Get();
                return View(data);
            }
            return RedirectToAction("Unauthorized", "ErrorPage");
        }

        //GET BY ID
        public IActionResult Details(int id)
        {
            //var data = myContext.Provinces.Include(x => x.Region).FirstOrDefault(x => x.Id.Equals(id));
            var data = ProvinceRepository.Get(id);
            return View(data);
        }
        //CREATE
        //GET
        public IActionResult Create()
        {
            return View(province);
        }

        //POST - ngirim data berupa data yang sesuai dengan di model
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Province province)
        {
            if (ModelState.IsValid)
            {
                //myContext.Provinces.Add(province);
                //var result = myContext.SaveChanges();
                var result = ProvinceRepository.Post(province);
                if (result > 0)
                    return RedirectToAction(nameof(Index));
            }
            return View(province);
        }

        //UPDATE
        //GET
        public IActionResult Edit(int id)
        {
            //var data = myContext.Provinces.Find(id);
            //return View(data);
            var data = ProvinceRepository.Get(id);
            return View(data);
        }

        //POST - ngirim data berupa data yang sesuai dengan di model
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, Province province)
        {
            if (ModelState.IsValid)
            {
                //var data = myContext.Provinces.Find(id);
                //data.Name = province.Name;
                //data.RegionId = province.RegionId;
                //myContext.Provinces.Update(data);
                //var result = myContext.SaveChanges();
                var result = ProvinceRepository.Put(id, province);
                if (result > 0)
                    return RedirectToAction("Index");
            }
            return View();
        }

        //DELETE
        //GET
        public IActionResult Delete(int id)
        {
            //var data = myContext.Provinces.Find(id);
            //return View(data);
            var data = ProvinceRepository.Get(id);
            return View(data);
        }

        //POST - ngirim data berupa data yang sesuai dengan di model
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirm(Province province)
        {
            //myContext.Provinces.Remove(province);
            //var result = myContext.SaveChanges();
            var result = ProvinceRepository.Delete(province);
                if (result > 0)
                    return RedirectToAction("Index");
            return View();
        }
    }
}

SIBKMNETMvc_WebApp/Views/Province/Create.cshtml
@model SIBKMNETMvc_WebApp.Models.Province

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Province</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" asp-controller="Province" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RegionId" class="control-label"></label>
                <select asp-for="RegionId" class ="form-control" asp-items="ViewBag.RegionId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SIBKMNETMvc_WebApp/Views/Province/Details.cshtml
@model SIBKMNETMvc_WebApp.Models.Province

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Province</h4>
    <hr />
    <dl class="row">
    <div>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Region)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Region.Id)
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Region.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Region.Name)
        </dd>
     </div>
    </dl>
</div>
<div>
    <a class="btn btn-primary btn-sm" href="/Province/Edit?id=">Edit</a>
    <a class="btn btn-primary btn-sm" href="/Province/Index">Back to List</a>
</div>

SIBKMNETMvc_WebApp/Views/Province/Index.cshtml
@model IEnumerable<SIBKMNETMvc_WebApp.Models.Province>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create" asp-controller="Province" href="/Province/Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Region)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Region.Name)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Region.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Region.Name)
            </td>
            <td>
                <a class="btn btn-primary btn-sm" href="/Province/Edit?id=">Edit</a>
                <a class="btn btn-primary btn-sm" href="/Province/Details?id=">Details</a>
                <a class="btn btn-primary btn-sm" href="/Province/Delete?id=">Delete</a>
                @*@Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })*@
            </td>
        </tr>
}
    </tbody>
</table>